; Trainer levels constants
BROCK_LEVEL    EQU 15
MISTY_LEVEL    EQU 20
SURGE_LEVEL    EQU 25
ERIKA_LEVEL    EQU 30
KOGA_LEVEL     EQU 40
SABRINA_LEVEL  EQU 45
BLAINE_LEVEL   EQU 50
GIOVANNI_LEVEL EQU 55