STARTER1 EQU SANDILE
STARTER2 EQU TIMBURR
STARTER3 EQU BELDUM
STARTER1_MICOLO EQU CATERMANO 	; NUEVO PARA MICOLO PROTA
STARTER2_MICOLO EQU DARK_PIKA	; NUEVO PARA MICOLO PROTA
STARTER3_MICOLO EQU MICOMON	; NUEVO PARA MICOLO PROTA
