; Elemental types
NORMAL   EQU $00
FIGHTING EQU $01
FLYING   EQU $02
POISON   EQU $03
GROUND   EQU $04
ROCK     EQU $05
STEEL    EQU $06 ; NUEVO PARA TIPOS NUEVOS
BUG      EQU $07
GHOST    EQU $08
UNK  EQU $09; NUEVO PARA STRUGGLE
FIRE     EQU $14
WATER    EQU $15
GRASS    EQU $16
ELECTRIC EQU $17
PSYCHIC  EQU $18
ICE      EQU $19
DRAGON   EQU $1A
DARK     EQU $1B ; NUEVO PARA TIPOS NUEVOS
UNKNOWN   EQU $1C ; NUEVO PARA TIPOS NUEVOS
