tbp: MACRO
	dbw BANK(\1), \1
	ENDM

	tbp Music_Nothing
	tbp Music_RBYPalletTown
	tbp Music_Pokecenter
	tbp Music_RBYGym
	tbp Music_Cities1
	tbp Music_Cities2
	tbp Music_Celadon
	tbp Music_Cinnabar
	tbp Music_Vermilion
	tbp Music_Lavender
	tbp Music_SSAnne
	tbp Music_MeetProfOak
	tbp Music_MeetRival
	tbp Music_MuseumGuy
	tbp Music_SafariZone
	tbp Music_PkmnHealed
	tbp Music_Routes1
	tbp Music_Routes2
	tbp Music_Routes3
	tbp Music_Routes4
	tbp Music_RBYIndigoPlateau
	tbp Music_GymLeaderBattle
	tbp Music_TrainerBattle
	tbp Music_WildBattle
	tbp Music_FinalBattle
	tbp Music_DefeatedTrainer
	tbp Music_DefeatedWildMon
	tbp Music_DefeatedGymLeader
	tbp Music_RBYTitleScreen
	tbp Music_RBYCredits
	tbp Music_RBYHallOfFame
	tbp Music_OaksLab
	tbp Music_JigglypuffSong
	tbp Music_BikeRiding
	tbp Music_Surfing
	tbp Music_RBYGameCorner
	tbp Music_IntroBattle
	tbp Music_Dungeon1
	tbp Music_Dungeon2
	tbp Music_Dungeon3
	tbp Music_CinnabarMansion
	tbp Music_PokemonTower
	tbp Music_SilphCo
	tbp Music_MeetEvilTrainer
	tbp Music_MeetFemaleTrainer
	tbp Music_MeetMaleTrainer
	; NUEVAS MUSICAS
	tbp Music_Cities1_Slow
	tbp Music_MeetRivalAltStart
	tbp Music_MeetRivalAltTempo
	tbp Music_MeetRivalAltStartAndTempo
	tbp Music_MotherBeastBattle
	tbp Music_HeartMulholland
	tbp Music_FrontierBrain
	tbp Music_RocketBattle
	tbp Music_SuicuneBattle
	tbp Music_Pinballgengarstage_gastly
	tbp Music_HoennWild
	tbp Music_JohtoWildBattle
	tbp Music_SinnohWildBattle
	tbp Music_WildBattleSM
	tbp Music_BWWild
	tbp Music_CCCP
	tbp Music_20thCenturyFox_flauta
	tbp Music_MadWorld
	tbp Music_AlolaEliteFourBattle
	tbp Music_ChampionBattle_B2W2
	tbp Music_ZinniaBattle
	tbp Music_UnovaEliteFourBattle
	tbp Music_SinnohGameCorner
	tbp Music_TCGImakuni
	tbp Music_RivalBattle_XY
	tbp Music_FiestaPagana
	tbp Music_LookGladion
	tbp Music_EyesOfFlame
	tbp Music_SplatoonTheme
	tbp Music_MirorB
	tbp Music_SteelSamurai
	tbp Music_MAGruntBattle
	tbp Music_Guile
	tbp Music_OurHouse
	tbp Music_Cornered
	tbp Music_NGE
	tbp Music_NGE_Intro
	tbp Music_LaSantaEspina
	tbp Music_Contra
	tbp Music_LacunosaTown
	tbp Music_PetalburgCity
