TrainerNames:
	db "YOUNGSTER@"
	db "BUG CATCHER@"
	db "LASS@"
	db "SAILOR@"
	db "JR.TRAINER♂@"
	db "JR.TRAINER♀@"
	db "POKéMANIAC@"
	db "SUPER NERD@"
	db "HIKER@"
	db "BIKER@"
	db "BURGLAR@"
	db "ENGINEER@"
	db "JUGGLER@"
	db "FISHERMAN@"
	db "SWIMMER@"
	db "CUE BALL@"
	db "GAMBLER@"
	db "BEAUTY@"
	db "PSYCHIC@"
	db "ROCKER@"
	db "JUGGLER@"
	db "TAMER@"
	db "BIRD KEEPER@"
	db "BLACKBELT@"
	db "RIVAL1@"
	db "PROF.OAK@"
	db "CHIEF@"
	db "SCIENTIST@"
	db "GIOVANNI@"
	db "ROCKET@"
	db "COOLTRAINER♂@"
	db "COOLTRAINER♀@"
	db "BRUNO@"
	db "BROCK@"
	db "MISTY@"
	db "LT.SURGE@"
	db "ERIKA@"
	db "KOGA@"
	db "BLAINE@"
	db "SABRINA@"
	db "GENTLEMAN@"
	db "RIVAL2@"
	db "RIVAL3@"
	db "LORELEI@"
	db "CHANNELER@"
	db "AGATHA@"
	db "LANCE@"
	db "RAGU@" 	; NUEVO AÑADIENDO UN ENTRENADOR
	db "GOLDY@" 	; NUEVO AÑADIENDO UN ENTRENADOR
	db "UTALAWEA@" 	; NUEVO AÑADIENDO UN ENTRENADOR
	db "EEVEETO@" 	; NUEVO AÑADIENDO UN ENTRENADOR
	db "JAVISIT@" 	; NUEVO AÑADIENDO UN ENTRENADOR
	db "MANEC@" ; NUEVO AÑADIENDO UN ENTRENADOR
	db "DARKI@" ; NUEVO AÑADIENDO UN ENTRENADOR
	db "GOOSES@" ; NUEVO AÑADIENDO UN ENTRENADOR
	db "KAISSER@" ; NUEVO AÑADIENDO UN ENTRENADOR
	db "slowbro@" ; NUEVO AÑADIENDO UN ENTRENADOR
	db "DUNK@" ; NUEVO AÑADIENDO UN ENTRENADOR
	db "PACOCHEF@" ; NUEVO AÑADIENDO UN ENTRENADOR
	db "KADERETE@" ; NUEVO AÑADIENDO UN ENTRENADOR
	db "KRUB@" ; NUEVO AÑADIENDO UN ENTRENADOR
	db "LAVENDER@" ; NUEVO AÑADIENDO UN ENTRENADOR
	db "M.DRAGON@" ; NUEVO AÑADIENDO UN ENTRENADOR
	db "SJMISTERY@" ; NUEVO AÑADIENDO UN ENTRENADOR
	db "RUBENCB@" ; NUEVO AÑADIENDO UN ENTRENADOR
	db "TRAINER BOT@" ; NUEVO AÑADIENDO UN ENTRENADOR
	db "GRIM@" ; NUEVO AÑADIENDO UN ENTRENADOR
	db "FURRY@" ; NUEVO AÑADIENDO UN ENTRENADOR
	db "M.ARENA@"  ; NUEVO AÑADIENDO UN ENTRENADOR
	db "VLADILAND@" ; NUEVO AÑADIENDO UN ENTRENADOR
	db "JPROGAMER@"  ; NUEVO AÑADIENDO UN ENTRENADOR
	db "TSURUKO@"  ; NUEVO AÑADIENDO UN ENTRENADOR
	db "ALBERMAUS@"  ; NUEVO AÑADIENDO UN ENTRENADOR
	db "MERUM@"  ; NUEVO AÑADIENDO UN ENTRENADOR
	db "SAPPHIRE@" ; NUEVO AÑADIENDO UN ENTRENADOR
	db "DOBLEC@" ; NUEVO AÑADIENDO UN ENTRENADOR
	db "JZOMBIE@"  ; NUEVO AÑADIENDO UN ENTRENADOR
	db "MERCIBOKU@" ; NUEVO AÑADIENDO UN ENTRENADOR
	db "RAZ y LAV@" ; NUEVO AÑADIENDO UN ENTRENADOR
	db "KRAFT@" ; NUEVO AÑADIENDO UN ENTRENADOR
	db "GARM@" ; NUEVO AÑADIENDO UN ENTRENADOR
	db "SANTYGRASS@" ; NUEVO AÑADIENDO UN ENTRENADOR
	db "FELIPEX@" ; NUEVO AÑADIENDO UN ENTRENADOR
	db "ARTHEMIS@" ; NUEVO AÑADIENDO UN ENTRENADOR
	db "KASTY@" ; NUEVO AÑADIENDO UN ENTRENADOR
	db "JOEL@" ; NUEVO AÑADIENDO UN ENTRENADOR
	db "FXOZ@" ; NUEVO AÑADIENDO UN ENTRENADOR
	db "PHENT@" ; NUEVO AÑADIENDO UN ENTRENADOR
	db "MICOLO@" ; NUEVO AÑADIENDO UN ENTRENADOR
	db "AngelFS@" ; NUEVO AÑADIENDO UN ENTRENADOR
	db "BLUE@" ; NUEVO AÑADIENDO UN ENTRENADOR
	db "YELLOW@" ; NUEVO AÑADIENDO UN ENTRENADOR
	db "A.VADER@" ; NUEVO AÑADIENDO UN ENTRENADOR
	db "MIROR B.@" ; NUEVO AÑADIENDO UN ENTRENADOR
	db "SAULGP@" ; NUEVO AÑADIENDO UN ENTRENADOR
	db "CHARZ@" ; NUEVO AÑADIENDO UN ENTRENADOR
	db "ISMAPKM@"; NUEVO AÑADIENDO UN ENTRENADOR
	db "MLKORLDVRDAD@";  NUEVO AÑADIENDO UN ENTRENADOR
	db "MICHOH@";  NUEVO AÑADIENDO UN ENTRENADOR
	db "FANBOY@"; NUEVO AÑADIENDO UN ENTRENADOR
	db "HATER@";  NUEVO AÑADIENDO UN ENTRENADOR
	db "HYPEANTO@";  NUEVO AÑADIENDO UN ENTRENADOR
	db "ESCROTO@";  NUEVO AÑADIENDO UN ENTRENADOR
	db "ENTROPIA@";  NUEVO AÑADIENDO UN ENTRENADOR
